---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: referencia-frontend
  labels:
    app: referencia-frontend
    part-of: pdpj-referencia
spec:
  selector:
    matchLabels:
      app: referencia-frontend
      part-of: pdpj-referencia
  template:
    metadata:
      labels:
        app: referencia-frontend
        part-of: pdpj-referencia
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: referencia-frontend
                  part-of: pdpj-referencia
              topologyKey: kubernetes.io/hostname
      containers:
      - name: referencia-frontend
        image: registry.cnj.jus.br/pdpj/referencia-frontend:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/Sao_Paulo
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 20
          periodSeconds: 30
          timeoutSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
        - name: referencia-frontend-config
          mountPath: /usr/share/nginx/html/assets/config
          readOnly: true
      imagePullSecrets:
      - name: registry-cnj
      volumes:
      - name: referencia-frontend-config
        configMap:
          name: referencia-frontend-config
...
---
apiVersion: v1
kind: Service
metadata:
  name: referencia-frontend
  labels:
    app: referencia-frontend
    part-of: pdpj-referencia
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  selector:
    app: referencia-frontend
    part-of: pdpj-referencia
...
