---
apiVersion: v1
kind: ConfigMap
metadata:
  name: referencia-frontend-config
  labels:
    app: referencia-frontend
    part-of: pdpj-referencia
data:

  env.js: |
    (function (window) {
      window.__env = window.__env || {};
      window.__env.production = false;
      window.__env.nome = "Projeto de ReferÊncia";
      window.__env.descricao = "Projeto de Referência";
      window.__env.apiUrl = "https://gateway.stg.cloud.pje.jus.br/referencia/api/v1", //<-Backend
      window.__env.ssoUrl = "https://sso.stg.cloud.pje.jus.br/auth/",
      window.__env.realm = "pje",
      window.__env.clientId = "referencia-frontend",
      window.__env.redirectUri = "http://referencia.stg.pdpj.jus.br"
    }(this));

...
